### ISSUE TITLE
Camera rotation

### ISSUE THREAD

**Issue by Edge231** [timpiglowski/prusa-connect-webcam#1]
I've been trying various codes and scripts from other devs but this is the first one to work for me so big thanks.  :)   

My question is about the image output.  The script is successfully outputting the image to Prusa Connect, but it's currently rotated by 90 degrees so I have to tilt my head to the right to view it in a normal orientation.  Can the image be rotated via the docker-compose.yml code, or is there a specific command to run before the script is running to rotate the camera output?  Using a Logitech C922x for reference, and it's installed on a small bracket facing the front of the printer in a normal orientation.

**Comment by Edge231** [comment]
Update:  this seems to be perhaps a browser issue and not the script or the pi doing this.  When I look at the camera feed through the Prusa app on my phone, it's in the correct orientation.  Closing this for now since there's nothing you can do about a browser issue.  Thanks anyway though!

**Comment by timpiglowski** [comment]
Hey there,Thank you so much for taking the time to write these two mails. It’s the first time, I got any feedback on one of my projects, so I really appreciate it.Glad to hear the issue is resolved already, but I think I will add rotation regardless. Maybe it’s useful to someone.Have a nice week.TimAm 22.11.2024 um 21:21 schrieb Edge231 ***@***.***>:﻿
Update:  this seems to be perhaps a browser issue and not the script or the pi doing this.  When I look at the camera feed through the Prusa app on my phone, it's in the correct orientation.  Closing this for now since there's nothing you can do about a browser issue.  Thanks anyway though!
